# Generated by Django 5.2 on 2025-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dojo_ninja_delete_author_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='ninja_count',
            field=models.IntegerField(default=0),
        ),
    ]
